# pipeline to build empty IP address list
# list is used to manage IP deployments to LZs


trigger: none

pool: default

stages:
- stage: Init
  jobs:
  - job: CreateSubscription
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - script: |
        git config user.name "azuredevops"
        git config user.email "azure@devops"

        git switch -
        git checkout main
        git status
        git config pull -rebase false
        git pull origin main
        echo "Config update $(Build.BuildId)" > build.txt
      displayName: 'Enable script permissions'

    - bash: |
        git add --all
        git commit -m "Config update $(Build.BuildId)"
        git push origin main
        git status
      displayName: Git Commit
