# pipeline to build empty IP address list
# list is used to manage IP deployments to LZs


trigger: none

pool:  
  vmImage: ubuntu-latest

stages:
- stage: Init
  jobs:
  - job: TestGitpush
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - script: |
        git config user.name "azuredevops"
        git config user.email "azure@devops"

        echo "Config update $(Build.BuildId)" > build.txt
      displayName: 'Enable script permissions'

    - bash: |
        git add --all
        git commit -m "Config update $(Build.BuildId)"
        git push origin main
        git status
      displayName: Git Commit
