
pool:  
  vmImage: ubuntu-latest

stages:
- stage: Init
  jobs:
  - job: TestGitpush
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - script: |
        git fetch --all
        git switch $(basename $(Build.SourceBranch))
        git config user.name "azuredevops"
        git config user.email "azure@devops"
        echo "Config update $(Build.BuildId)" > build.txt
        git add .
        echo "commit"
        git commit -m "Config update $(Build.BuildId)"

        git push origin main

      displayName: Git Commit
